; ============================================================
;  Vent Controller v4.2 — PlatformIO project (ESP32, Arduino)
; ============================================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.7
    madhephaestus/ESP32Servo @ ^1.1.1
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    tzapu/WiFiManager @ ^2.0.16-rc.2
    esphome/ESPAsyncWebServer-esphome @ ^3.2.0
    esphome/AsyncTCP-esphome @ ^2.0.1

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
